#!/usr/bin/env bash
# This script is displaying Best School under a while loop and replace the ninth iterationi
COUNTER=0
MAX_COUNTER=9
ITERATION_STOP=8
while [ $COUNTER -le $MAX_COUNTER ];
do
	if [ $COUNTER -eq $ITERATION_STOP ]; 
		echo "Hi"
	else
		echo "Best School"
	fi
	((COUNTER++))
done

