#!/usr/bin/env bash
# This script is displaying Best School under a while loop and replace the ninth iterationi
COUNTER=0
MAX_COUNTER=9
BAD_LUCK_ITERATION=3
GOOD_LUCK_ITERATION=7
while [ $COUNTER -le $MAX_COUNTER ];
do
	if [ $COUNTER -eq $BAD_LUCK_ITERATION ]; then 
		echo "bad luck"
	elif [ $COUNTER -eq $GOOD_LUCK_ITERATION ]; then
		echo "good luck"
	else 
		echo "Best School"
	fi
	((COUNTER++))
done
