#!/usr/bin/env bash
# This script is displaying Best School under a while loop and replace the ninth iterationi
COUNTER=0
MAX_COUNTER=20
BAD_CHINA_ITERATION=4
BAD_JAPAN_ITERATION=9
BAD_ITALY_ITERATION=17
while [ $COUNTER -le $MAX_COUNTER ];
do
	case $COUNTER in
		$BAD_CHINA_ITERATION)
			echo "bad luck from China"
			;;
		$BAD_JAPAN_ITERATION)
			echo "bad luck from Japan"
			;;
		$BAD_ITALY_ITERATION)
			echo "bad luck from Italy"
			;;
		*)
			echo $COUNTER
			;;
		esac
	((COUNTER++))
done
