#!/usr/bin/env bash
#This script is used to print out a clocks numbers separated by hours and minutes

current_hour=0
current_minute=1
max_minute=20
max_hour=12

echo "Hour: $current_hour"
while [ $current_minute -le $max_minute ] && [ $current_hour -lt $max_hour ];
do
	echo "This is the current_minute: $current_minute"

	if [ $current_minute -eq $max_minute ]; then
		$current_minute=1
		echo "This is the minute after setting: $current_minute" 
		((current_hour++))
		echo "Hour: $current_hour"
	else 
		((current_minute++))
	fi
done 
