#!/usr/bin/env bash
# Script used to display directory contents split at the operator

example_string="Hello"

for (( i = 0; i < ${#example_string}; i++ ));
do
	current_character=${example_string:$i:1}"

	if [ current_character -eq "-" ]; then
		echo "Found special character"
	fi
done
