#!/usr/bin/env bash
# Script used to display directory contents split at the operator

has_found_update=false

for file in *;
do
	for (( i = 0; i < ${#file}; i++ ));
	do
		current_character="${file:$i:1}"

		if [ "$current_character" == "-" ]; then
			position=$((i+1))
			echo "${file:$position}"
			has_found_update=true
			break
		fi
	done

	if ! $has_found_update;
	 then
		echo "$file"
	fi

	has_found_update=false
done
