#!/usr/bin/env bash
#This script checks for the existince of a school file, empty, and if it's regular

found_file=false
for file in *;
do
	if [[ "$file" == "school"* ]]; 
	then
		found_file=true
		echo "school file exists"

		if [[ -s "$file" ]];
		then
			echo "school file is empty"
		else
			echo "school file is not empty"
		fi

		if [[ -f "$file"  ]];
		then
			echo "school is a regular file"
		fi

		break
	fi
done

if [[ ! $found_file  ]];
then
	echo "school file does not exist"
fi
