#!/usr/bin/env bash
# Used to kill bash proccess

# According to the script name kill the process in a new window`
script_name="7-highlander"
process_id=$(pgrep -f "$script_name")

kill "$process_id"
